# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-08 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='descriptions',
            field=models.TextField(default='descriptions default text'),
        ),
    ]
