# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-08 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profiles_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('descriptions', models.TextField(default='descriptions default text')),
                ('location', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='profiles',
        ),
    ]
