# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-08 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20180308_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='my locations default', max_length=120),
        ),
    ]
