# Generated by Django 2.0 on 2018-09-06 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20180825_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='file_type',
            new_name='song_type',
        ),
    ]
